from guizero import App, PushButton, Slider, Text, Picture
app = App(layout="grid")
picture1 = Picture(app, image="logo.jpg", grid=[0,0])
button1 = PushButton(app, text="1", grid=[8,8])
button2 = PushButton(app, text="2", grid=[9,8])
button3  = PushButton(app, text="3", grid=[10,8])
button4  = PushButton(app, text="4", grid=[8,9])
button5  = PushButton(app, text="5", grid=[9,9])
button6  = PushButton(app, text="6", grid=[10,9])
button7  = PushButton(app, text="7", grid=[8,10])
button8  = PushButton(app, text="8", grid=[9,10])
button9  = PushButton(app, text="9", grid=[10,10])
button0  = PushButton(app, text="0", grid=[9,11])
app.display()